### ISSUE TITLE
More generic execution API

### ISSUE THREAD

**Issue by aviks** [JuliaWeb/JuliaWebAPI.jl#18]
Currently, JuliaWebAPI works for functions that are exported via `process` and take `String` parameters. 

It _may_ be useful to have a mechanism where arbitrary functions (maybe limited to those with String and int/float params)  could be executed via JSON and the `APIInvoker`. 

cc: @tanmaykm @viralbshah Thoughts?

**Comment by tanmaykm** [comment]
@aviks The current design is to have the registered method take all string parameters and delegate after converting appropriately. I was unable to come up with any other good mechanism to handle different parameter types and methods with multiple signatures. Can you elaborate if you have an alternate way to achieve this?

**Comment by ViralBShah** [comment]
@aviks and I were talking about this a bit today. He is in Bangalore on Monday, and perhaps we can meet up and figure this out.

**Comment by tanmaykm** [comment]
Great! I'll be away, but do ping me if needed.

**Comment by aviks** [comment]
So currently, parameters of different types work to the extent of primitive JSON types.. ie String, integers and floats. That is all we want at the moment, I think, without implementing our own IDL. 

The other thing in this issue is the ability to invoke *any* function, rather than just those _registered_. However, that is policy question, the implementation is trivial. What do people feel about this?

**Comment by tanmaykm** [comment]
This should not break existing implementations, because of the `applicable` check.

Outside this PR's scope, I wonder if it would be possible to use method reflection to handle more cases.
This handles a specific case of array types e.g. the test won't pass if called with `[1 2; 3 4]` instead of `[1.0 2.0; 3.0 4.0]`.

**Comment by aviks** [comment]
Fixed by #40
