### ISSUE TITLE
Add to METADATA?

### ISSUE THREAD

**Issue by aviks** [JuliaWeb/JuliaWebAPI.jl#19]
I've used this for so long that I assumed this was in METADATA. Apparently it isn't. Lets add it? 

cc: @tanmaykm @bmharsha @viralbshah @mdpradeep

**Comment by tanmaykm** [comment]
Yes, will do it.

**Comment by sbromberger** [comment]
Would this be suitable for inclusion in the JuliaWeb organization?

**Comment by ViralBShah** [comment]
+1 to add to METADATA, and also to JuliaWeb.

**Comment by tkelman** [comment]
should update travis to the newer style and run tests on every supported minor ver

**Comment by tanmaykm** [comment]
Ok. Closing this now. Will resubmit after updating travis and moving to JuliaWeb.

**Comment by tanmaykm** [comment]
Oops, meant to close the PR to METADATA.

**Comment by tanmaykm** [comment]
closed via https://github.com/JuliaLang/METADATA.jl/issues/4136
