### ISSUE TITLE
ArgumentError: cannot convert NULL to string

### ISSUE THREAD

**Issue by audacyDevOps** [JuliaWeb/JuliaWebAPI.jl#23]
Hi, I re-run your example on a CentOS 7 with Julia v0.4.3, but encounter this error "cannot convert NULL to string". It seems that it is caused by a dependency HttpParser which can't parse integer. 

**Error Message**
julia> run_rest(apiclnt, 8000)
ERROR (unhandled task failure): ArgumentError: cannot convert NULL to string
 in on_header_value at /root/.julia/v0.4/HttpServer/src/RequestParser.jl:60
^Cfatal: error thrown and no exception handler available.

**Troubleshooting observation**
1. Based on https://github.com/JuliaWeb/Requests.jl/issues/75, it suggests the problem is with older version of HttpParser. One developer reports success after installing HttpParser v2.1. I don't know how to replace with v2.1, though I tried something like Pkg.add("HttpParser"), then Pkg.checkout, etc without lucks.  I checkout HttpParser from github, and build. It generates libhttpparser.so but i dont know where to copy to. CentOS7 Julia does not currently use libhttparser.so but it uses libhttpaser.so.2.

2. I test Pkg.test("HttpParser") with errors.
3. I installed Julia with cmake but it does not help resolving any issue.
4. I tried repeating your sample codes to create REST API by using Julia v0.5. same errors.

any pointer?  
thanks

**Comment by aviks** [comment]
discussion here: https://github.com/JuliaWeb/Requests.jl/issues/75#issuecomment-186826952

**Comment by tanmaykm** [comment]
Fixed in JuliaWebAPI v0.0.3 (tested on CentOS 7.2)
