### ISSUE TITLE
Error running example from README

### ISSUE THREAD

**Issue by jw3126** [JuliaWeb/JuliaWebAPI.jl#35]
If I try to run the example from the readme, I get
```
julia srvr.jl &
```

```
ERROR: LoadError: ArgumentError: invalid value for Enum LogLevel: 1
 in enum_argument_error(::Symbol, ::Int32) at ./Enums.jl:27
 in convert(::Type{Logging.LogLevel}, ::Int32) at ./Enums.jl:79
 in (::JuliaWebAPI.#kw##process)(::Array{Any,1}, ::JuliaWebAPI.#process, ::Array{Tuple{Function,Bool},1}, ::String) at ./<missing>:0
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318

```

**Comment by tanmaykm** [comment]
The default log level specification is broken after https://github.com/kmsquire/Logging.jl/pull/21. Needs a fix [here](https://github.com/JuliaWeb/JuliaWebAPI.jl/blob/1dc4032b25bc79aeb0111362b15fbf5d6a61c813/src/APIResponder.jl#L180) and [here](https://github.com/JuliaWeb/JuliaWebAPI.jl/blob/1dc4032b25bc79aeb0111362b15fbf5d6a61c813/src/APIResponder.jl#L215)

Specifying the log level explicitly can be a work around in the meantime:
````julia
# ...
using Logging
process([(testfn1, true), (testfn2, false)], "tcp://127.0.0.1:9999";
        bind=true, log_level=INFO)
````

**Comment by jw3126** [comment]
I can reproduce the example now, thanks!
