### ISSUE TITLE
How to terminate server process?

### ISSUE THREAD

**Issue by guilhermebodin** [JuliaWeb/JuliaWebAPI.jl#77]
I saw that the command to terminate the server is `:terminate` but this is not a valid command.
```julia
function isvalidcmd(cmd)
    isempty(cmd) && return false
    Base.is_id_start_char(cmd[1]) || return false
    for c in cmd
        Base.is_id_char(c) || return false
    end
    true
end
```
because this function returns false
```julia
Base.is_id_start_char(':')
```
is there another way?

**Comment by tanmaykm** [comment]
Thanks @guilhermebodin for reporting.
This should be fixed with #75. 
A new version v0.6.1 is [tagged](https://github.com/JuliaRegistries/General/pull/7077) as well.
